name: 'analytics_portfolio'
version: '1.0.0'
config-version: 2
profile: 'analytics_portfolio'

model-paths: ["dbt_models"]
target-path: "target"

models:
  analytics_portfolio:
    +materialized: view
    mrt:
      +materialized: table
